### ISSUE TITLE
Unable to start Camera UI - Logger.warn is not a function

### ISSUE THREAD

**Issue by mynameisdaniel32** [seydx/homebridge-camera-ui#381]
**Describe the bug**
Since updating to v5.0.10 this morning, I'm getting the below error when Homebridge tries to start the Camera UI plugin.
I'm not sure what's triggering the Logger.warn, but it's not happy with the function.

Looks like the change from `logger` to `Logger` has caused this?

Disabling Camera UI allows Homebridge to start okay.

**To Reproduce**
Tried a fresh install of both Homebridge and Camera UI plugin, both running latest stable.

**Expected behavior**
Not to crash.

**Logs**
Homebridge logs:
```
[22/01/2022, 9:52:11 am] [CameraUI] Initializing CameraUI platform...
[22/01/2022, 9:52:11 am] TypeError: Logger.warn is not a function
    at file:///usr/lib/node_modules/homebridge-camera-ui/services/config/config.service.js:26:20
    at Array.map (<anonymous>)
    at new ConfigSetup (file:///usr/lib/node_modules/homebridge-camera-ui/services/config/config.service.js:15:8)
    at new HomebridgeCameraUI (file:///usr/lib/node_modules/homebridge-camera-ui/src/platform.js:44:19)
    at /usr/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
```

**Environment**
- Node.js Version: v16.13.2
- Homebridge Version: v1.4.0
- Camera UI Version: v5.0.10
- Operating System: Debian Linux
- Browser: N/A

**Comment by seydx** [comment]
fixed in v5.0.11
