### ISSUE TITLE
Socket.io.emit.emit is not a function

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#539]
After update to 5.0.26

```
[24.04.2022, 16:37:40] [CameraUI]  ERROR  TypeError: Socket.io.emit.emit is not a function
TypeError: Socket.io.emit.emit is not a function
    at Pipe2Pam.<anonymous> (file:///usr/lib/node_modules/homebridge-camera-ui/node_modules/camera.ui/src/controller/camera/services/videoanalysis.service.js:318:22)
    at Pipe2Pam.emit (node:events:526:28)
    at Pipe2Pam._findPam (/usr/lib/node_modules/homebridge-camera-ui/node_modules/pipe2pam/index.js:81:18)
    at Pipe2Pam._transform (/usr/lib/node_modules/homebridge-camera-ui/node_modules/pipe2pam/index.js:112:10)
    at Pipe2Pam.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Pipe2Pam.Writable.write (node:internal/streams/writable:334:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by slimemold** [comment]
I'm seeing this same exact thing as well.

**Comment by seydx** [comment]
You are all way too fast :D I wanted to release the version as beta, mistyped it

Should all work again with v5.0.27

Sorry :P

**Comment by grzegorz914** [comment]
Working again

Thanks
